# Generated by Django 5.0.3 on 2024-03-24 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='chair',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='event',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='row',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='minAge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='capacity_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='capacity_standing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='userTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_app.usermodel'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='registerDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=30)),
                ('entryTime', models.DateTimeField()),
                ('eventTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_app.eventmodel')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='categoryTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_app.ticketcategory'),
        ),
    ]
