# Generated by Django 5.0.4 on 2024-06-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
