# Generated by Django 5.0.3 on 2024-03-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_user_alter_ticket_userto_delete_usermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registerDate',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
